[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vineyard_wind" # Replace with your desired project name
version = "0.0.1"
description = "A local Python package for project imports"
authors = [{ name = "William F. Jenkins", email = "wfjenkins@ucsd.edu" }]
dependencies = [
    "basemap",
    "basemap-data-hires",
    "bathyreq",
    "cmasher",
    "cmocean",
    "h5py",
    "ipympl",
    "juliacall",
    "jupyterlab",
    "matplotlib",
    "numpy",
    "piecewise-regression",
    "polars",
    "pyarrow",
    "pydantic",
    "pymap3d",
    "pyproj",
    "python-dotenv",
    "scikit-learn",
    "scipy",
    "tqdm",
    "rodeo",
    "seaborn",
    "TritonOA",
]
requires-python = ">= 3.12"

[project.optional-dependencies]
annotator = ["dash", "dash-bootstrap-components", "plotly"]

[project.scripts]
workflow = "vineyard.workflow:main"
annotator = "vineyard.annotator:main"

[tool.uv.sources]
rodeo = { path = "../core", editable = true }
TritonOA = { git = "ssh://git@github.com/TritonOA/TritonOA.git" }

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/vineyard"]
