[build-system]
requires = ["setuptools >= 80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vwdas"  # Replace with your desired project name
version = "0.0.1"
description = "A local Python package for project imports"
authors = [
    { name = "William F. Jenkins", email = "wfjenkins@ucsd.edu" }
]
dependencies = []  # Add any dependencies here
requires-python = ">= 3.12"

[tool.setuptools.packages.find]
where = ["src"]  # Specifies where to find the package