[metadata]
sensor_data = "data/sensors.csv"
turbine_data = "data/turbines.csv"
source_pile = "AN36"
calibration_dir = "data/acoustic/calibration/"

[etl]
distances = "data/distances.csv"
inventory_config = "config/inventory.toml"
inventory_dir = "data/acoustic/"
ref_mooring = "VLA1"

[etl.bathymetry]
bounds = [[-71.0, -68.999], [39.5, 41.601]]
output_path = "data/bathy/bathy.hdf5"
xres = 800
yres = 800

[process]

start_time = "2023-12-01T21:06:00.00"
end_time = "2023-12-01T22:26:00.00"
time_ranges = [
    [
        "2023-12-01T21:06:55.00",
        "2023-12-01T21:09:30.00",
    ],
    [
        "2023-12-01T21:09:50.00",
        "2023-12-01T21:11:20.00",
    ],
    [
        "2023-12-01T21:11:45.00",
        "2023-12-01T21:16:00.00",
    ],
    [
        "2023-12-01T21:16:15.00",
        "2023-12-01T21:18:15.00",
    ],
    [
        "2023-12-01T21:18:45.00",
        "2023-12-01T21:24:55.00",
    ],
    [
        "2023-12-01T21:25:20.00",
        "2023-12-01T21:31:40.00",
    ],
    [
        "2023-12-01T21:32:00.00",
        "2023-12-01T21:36:10.00",
    ],
    [
        "2023-12-01T21:36:20.00",
        "2023-12-01T21:41:20.00",
    ],
    [
        "2023-12-01T21:41:40.00",
        "2023-12-01T21:45:15.00",
    ],
    [
        "2023-12-01T21:45:30.00",
        "2023-12-01T21:47:15.00",
    ],
    [
        "2023-12-01T21:51:20.00",
        "2023-12-01T22:26:00.00",
    ],
]

[process.strike]
strike_index = "data/acoustic/strikes/strike_index.csv"
strike_data = "data/acoustic/strikes/strike_data.h5"
strike_corr = "data/acoustic/strikes/strike_corr"

[process.strike.find]
sensors = [
    { name = "3dvha", channel = 7, distance_s = 1.0, threshold = 0.05 },
    { name = "vla1", channel = 3, distance_s = 1.0, threshold = 0.05 },
    { name = "vla2", channel = 0, distance_s = 1.0, threshold = 0.02 },
]
taper_pc = 2e-4
filt_type = "bandpass"
filt_freq = [100.0, 300.0]

[process.strike.save]
buffer_start = 1.1
buffer_end = 0.9

[process.strike.correlation]
max_workers = 10
detrend = true
dec_factor = 20
taper_pc = 0.05
filt_type = "bandpass"
filt_freq = [15.0, 300.0]

[process.template]
sensors = [
    { name = "3dvha", channel = 7, ylim = [
        -0.05,
        0.05,
    ] },
    { name = "vla1", channel = 3, ylim = [
        -2.5e-7,
        2.5e-7,
    ] },
    { name = "vla2", channel = 0, ylim = [
        -1.5e-7,
        1.5e-7,
    ] },
]
buffer_start = 0.8
buffer_end = 1.0
filt_type = "bandpass"
filt_freq = [15.0, 50.0]
corr_cutoff = 0.75
window_size = 20
max_shift = 0.1
plot_dir = "reports/figures/strike_templates/"
template_data = "data/acoustic/templates/strike_templates.h5"

[process.denoise]
denoised_data = "data/acoustic/denoised/"
sensors = [
    { name = "3dvha", channel = 7 },
    { name = "vla1", channel = 3 },
    { name = "vla2", channel = 0 },
]
filt_type = "bandpass"
filt_freq = [15.0, 50.0]
buffer_start = 0.8
buffer_end = 1.0
template_taper_pc = 0.05

[process.whale_template]
template_data = "data/acoustic/templates/whale_templates.h5"
filt_type = "bandpass"
filt_freq = [15.0, 50.0]
taper_pc = 0.15

[process.whale_template.calls.3dvha]
channel = 7
type1 = { start = "2023-12-01T23:14:27.70", end = "2023-12-01T23:14:29.20" }
type2 = { start = "2023-12-01T22:25:46.10", end = "2023-12-01T22:25:47.10" }

[process.whale_template.calls.vla1]
channel = 3
type1 = { start = "2023-12-01T23:14:27.85", end = "2023-12-01T23:14:29.05" }
type2 = { start = "2023-12-01T22:25:55.52", end = "2023-12-01T22:25:56.90" }

[process.whale_template.calls.vla2]
channel = 0
type1 = { start = "2023-12-01T23:14:26.25", end = "2023-12-01T23:14:28.00" }
type2 = { start = "2023-12-01T22:25:55.08", end = "2023-12-01T22:25:56.39" }

[process.whale_detection]
sensors = [
    { name = "3dvha", distance_s = 7.0, threshold = 0.25 },
    { name = "vla1", distance_s = 7.0, threshold = 0.15 },
    { name = "vla2", distance_s = 7.0, threshold = 0.3 },
]
channel = 5
filt_type = "bandpass"
filt_freq = [15.0, 50.0] # Hz
output_file = "data/acoustic/whale_detections.csv"

[tdoa]
localization_file = "data/acoustic/tdoa/localization.csv"
reference_site = "vla1"
ambiguity_lower_bound = 90.0                              # degrees
ambiguity_upper_bound = 270.0                             # degrees
dwdt_threshold = 0.25                                     # degrees per second
smoothing_window = 10                                     # number of calls
speed_upper_bound = 35.0                                  # km/h

[plotting]
savefig_kwargs = { bbox_inches = "tight", dpi = 300, facecolor = "white" }
mpl_style = "config/scirep_fig_style.mplstyle"

# [plotting.map]
# output = "reports/figures/maps/map.png"

[plotting.signal_template]
col_titles = ["3DVHA", "VLA1", "VLA2"]
whale_sensors = [
    { name = "3dvha", channel = 7, peak_time = "2023-12-01T22:25:46.60", start_buffer = 1.5, end_buffer = 1.5 },
    { name = "vla1", channel = 3, peak_time = "2023-12-01T22:25:56.20", start_buffer = 1.5, end_buffer = 1.5 },
    { name = "vla2", channel = 0, peak_time = "2023-12-01T22:25:55.75", start_buffer = 1.5, end_buffer = 1.5 },
]
strike_sensors = [
    { name = "3dvha", channel = 7, peak_time = "2023-12-01T22:23:45.60", start_buffer = 1.5, end_buffer = 1.5 },
    { name = "vla1", channel = 3, peak_time = "2023-12-01T22:23:56.20", start_buffer = 1.5, end_buffer = 1.5 },
    { name = "vla2", channel = 0, peak_time = "2023-12-01T22:23:55.75", start_buffer = 1.5, end_buffer = 1.5 },
]
filt_type = "bandpass"
filt_freq = [9.0, 110.0]
nperseg = 16384
hop = 32
flim = [10.0, 90.0]
whale_ylim = [-3e7, 3e7]
strike_ylim = [-3e8, 3e8]
figsize = [9, 6]

output = "reports/figures/signal_templates.png"
