[metadata]
sensor_data = "data/sensors.csv"
turbine_data = "data/turbines.csv"

[etl]
distances = "data/distances.csv"
inventory_config = "config/inventory.toml"
inventory_dir = "data/acoustic/"

[etl.bathymetry]
bounds = [[-71.0, -68.999], [39.5, 41.601]]
output_path = "data/bathy/bathy.hdf5"
xres = 800
yres = 800

[process]

time_ranges = [
    [
        "2023-12-01T21:06:55.00",
        "2023-12-01T21:09:30.00",
    ],
    [
        "2023-12-01T21:09:50.00",
        "2023-12-01T21:11:20.00",
    ],
    [
        "2023-12-01T21:11:45.00",
        "2023-12-01T21:16:00.00",
    ],
    [
        "2023-12-01T21:16:15.00",
        "2023-12-01T21:18:15.00",
    ],
    [
        "2023-12-01T21:18:45.00",
        "2023-12-01T21:24:55.00",
    ],
    [
        "2023-12-01T21:25:20.00",
        "2023-12-01T21:31:40.00",
    ],
    [
        "2023-12-01T21:32:00.00",
        "2023-12-01T21:36:10.00",
    ],
    [
        "2023-12-01T21:36:20.00",
        "2023-12-01T21:41:20.00",
    ],
    [
        "2023-12-01T21:41:40.00",
        "2023-12-01T21:45:15.00",
    ],
    [
        "2023-12-01T21:45:30.00",
        "2023-12-01T21:47:15.00",
    ],
    [
        "2023-12-01T22:16:00.00",
        "2023-12-01T22:26:00.00",
    ],
]

[process.strike]
strike_index = "data/acoustic/strikes/strike_index.csv"
strike_data = "data/acoustic/strikes/strike_data.h5"
strike_corr = "data/acoustic/strikes/strike_corr"

[process.strike.find]
sensors = [
    { name = "3dvha", channel = 7, distance_s = 1.0, threshold = 0.05 },
    { name = "vla1", channel = 3, distance_s = 1.0, threshold = 0.05 },
    { name = "vla2", channel = 0, distance_s = 1.0, threshold = 0.02 },
]
taper_pc = 2e-4
filt_type = "bandpass"
filt_freq = [100.0, 300.0]

[process.strike.save]
buffer_start = 1.1
buffer_end = 0.9

[process.strike.correlation]
max_workers = 10
detrend = true
taper_pc = 0.05
dec_factor = 20
filt_type = "bandpass"
filt_freq = [15.0, 30.0]

[process.template]
sensors = [
    { name = "3dvha", channel = 7, ylim = [
        -0.015,
        0.015,
    ] },
    { name = "vla1", channel = 3, ylim = [
        -1.0e7,
        1.0e7,
    ] },
    { name = "vla2", channel = 0, ylim = [
        -5.0e6,
        5.0e6,
    ] },
]
start_time = "2023-12-01T21:06:00.00"
end_time = "2023-12-01T22:26:00.00"
buffer_start = 1.1
buffer_end = 0.9
corr_cutoff = 0.75
window_size = 35
plot_dir = "reports/figures/strike_templates/"
template_data = "data/acoustic/templates/strike_templates.h5"

[process.whale_template]
template_data = "data/acoustic/templates/whale_templates.h5"

[process.whale_template.calls.3dvha]
channel = 7
type1 = { start = "2023-12-01T23:14:27.7", end = "2023-12-01T23:14:29.2" }
type2 = { start = "2023-12-01T22:25:46.10", end = "2023-12-01T22:25:47.10" }

[process.whale_template.calls.vla1]
channel = 3
type1 = { start = "2023-12-01T23:14:27.85", end = "2023-12-01T23:14:29.05" }
type2 = { start = "2023-12-01T22:25:55.52", end = "2023-12-01T22:25:56.90" }

[process.whale_template.calls.vla2]
channel = 0
type1 = { start = "2023-12-01T23:14:26.25", end = "2023-12-01T23:14:28.00" }
type2 = { start = "2023-12-01T22:25:55.08", end = "2023-12-01T22:25:56.39" }

[process.denoise]
denoised_data = "data/acoustic/denoised/"
start = "2023-12-01T21:06:00.00"
end = "2023-12-01T22:26:00.00"
sensors = [
    { name = "3dvha", channel = 7 },
    { name = "vla1", channel = 3 },
    { name = "vla2", channel = 0 },
]
filt_type = "bandpass"
filt_freq = [15.0, 30.0]
buffer_start = 1.1
buffer_end = 0.9
