# ==============================================================================
[SHRU905_VLA1]

[SHRU905_VLA1.data]
directory = "./data/acoustic"
glob_pattern = "VLA1_SHRU905*/[!._]*.D23"
destination = "data/acoustic/SHRU905_VLA1_FileInfo.csv"
file_format = "SHRU"                                    # Optional

[SHRU905_VLA1.hydrophone] # Optional
fixed_gain = [6.0, 6.0, 6.0, 6.0]                        # dB
sensitivity = [203.9, 204.0, 203.9, 204.1]
serial_number = ["722017", "722019", "722020", "722022"]
# ==============================================================================
[SHRU920_VLA2]

[SHRU920_VLA2.data]
directory = "./data/acoustic"
glob_pattern = "VLA2_SHRU920*/[!._]*.D23"
destination = "data/acoustic/SHRU920_VLA2_FileInfo.csv"

[SHRU920_VLA2.hydrophone]
fixed_gain = [6.0, 6.0, 6.0, 6.0]
sensitivity = [204.0, 204.1, 204.0, 204.2]               # dB
serial_number = ["722013", "722014", "722015", "722016"]
