# Configuration file for paths used in the RODEOII project.
# [default] section contains paths shared across all computers.
# [computer.<name>] sections are paths for specific computers.

[default]
# Map bounds
bounds_file = "./config/map_bounds.toml"
# Bathymetry data
bathy_data = "./data/bathy/bathy.hdf5"
# Figures
figures = "./reports/figures"
jasa_style = "./config/jasa_fig_style.mplstyle"
# Equipment
equipment_config = "./config/experiment/equipment.csv"
# Acoustic Arrays
3dvha = "./config/experiment/3dvha.csv"
vla1_config = "./config/experiment/vla1.csv"
vla2_config = "./config/experiment/vla2.csv"
# DAS Location
das_location_raw = "./data/raw/DAS_final.h5"
das_location = "./config/experiment/das_location.csv"
# Turbine Locations
raw_turbine_data = "./data/turbines.csv"
turbine_config = "./config/experiment/turbines.csv"
# Acoustic Data Inventory
inventory_config = "./config/inventory.toml"
vla1_inventory = "./data/acoustic/inventory_SHRU905_VLA1.csv"
vla2_inventory = "./data/acoustic/inventory_SHRU920_VLA2.csv"
3dvha_inventory = "./data/acoustic/inventory_3DVHA.csv"
# Acoustic Data View
all_data_view = "./data/acoustic/data_view/all"
3dvha_data_view = "./data/acoustic/data_view/3DVHA"
vla1_data_view = "./data/acoustic/data_view/VLA1"
vla2_data_view = "./data/acoustic/data_view/VLA2"
# Acoustic Data
acoustic_data = "./data/acoustic/"
# 3DVHA Motion Data
vector_sensor_imu_processed = "data/acoustic/3dvha/vector_sensor_imu.csv"
# Dispersion data path
dispersion_dir = "./data/dispersion"
# Root path for pulse metrics
metrics_file = "./results/metrics.csv"
metrics_tex_file = "./reports/hdr_report/appendix_metrics/table.tex"
# Detector configurations
detector_config_dir = "./config/events"
# Pile-driving strike index
strike_index = "./data/acoustic/strike_index.csv"
strike_data = "./data/acoustic/strike_data.hdf5"
strike_corr = "./data/acoustic/strike_corr_19-25.hdf5"
synth_strikes = "./data/acoustic/"
# Template configuration
template_config = "./config/events/templates.csv"
template_data = "./data/acoustic/templates.hdf5"
# Event Index
event_config = "./config/events/events.csv"
# Meteorological data
wave_data = "./data/met/44085h2023.txt"
wind_data = "./data/met/buzm3h2023.txt"
met_data = "./data/met/data.csv"
# Path for generic results
results_dir = "./results"
# Event results
event_results_dir = "./results/events"
# PSD Database
psd_db = "./data/psd.hdf5"
amb_db = "./data/amb.hdf5"
# Max correlation databases
max_corr_dir = "./data/max_corr"

[computer.neptune]
# SHRU Data Directory
shru_data = "/Volumes/T7_Shield/RODEOII/south_fork/data/events"
# 3DVHA Motion Data
vector_sensor_imu_raw = "/Volumes/T7_Shield/RODEOII/vineyard/acoustic/3DVHA/motion"